name: Run Flask Tests with Docker Compose

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: docker compose -f docker-compose.test.yml up -d --build

      - name: Wait for Flask to be ready
        run: |
          echo "Waiting for Flask app..."
          until curl --silent --fail http://localhost:5000 > /dev/null; do
            sleep 2
          done
          echo "Flask is up!"

      - name: Run tests
        run: docker compose -f docker-compose.test.yml exec -T flask pytest --verbose

      - name: Tear down
        if: always()
        run: docker compose -f docker-compose.test.yml down
